### ISSUE TITLE
OSE_CAD implementation advice

### ISSUE THREAD

**Issue by earthgecko** [smirmik/CAD#3]
Hi @smirmik 

As per https://github.com/yzhao062/Pyod/issue_comments#issuecomment-411668090 I am looking to add OSE_CAD to https://github.com/earthgecko/skyline, as described in the issue.

Would it be possible to get your advice, suggestions or thoughts, either here or in https://gitter.im/earthgecko-skyline/Lobby on how I could best go about adding an implementation of OSE_CAD to Skyline from your perspective.

I am in the process of running through all the code, however I already know that it is going to take me a lot of work and time to understand each aspect of this method, which I **would** like to understand, however getting some advice from the author of the method cannot hurt :)

Anyway I hope that this may sound interesting enough for this conversation to be
continued.

PS - and very well done on winning the NAB competition!

**Comment by smirmik** [comment]
Please write to smirmik@gmail.com

**Comment by earthgecko** [comment]
Hi @smirmik  I would just like to say thank you for your time and the detailed overview, description and advice you provided me with  in our email conversation yesterday regarding the use of the current version of OSE_CAD, it was much appreciated.  Good luck with the future development of CAD, I will be watching with interest :)
